CREATE DATABASE App_Hubb;

USE App_Hubb;

CREATE TABLE user (
    email NVARCHAR(11) NOT NULL PRIMARY KEY,
    id VARCHAR(180),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE guest (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email NVARCHAR(11) NOT NULL,
    username VARCHAR(180),
    FOREIGN KEY(email) REFERENCES user(email) ON UPDATE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
